import { PERMISSIONS } from "./permissions.js";

export const ROLES = {
  user: [
    PERMISSIONS.AUTH_LOGOUT_SELF,
    PERMISSIONS.AUTH_LOGOUT_ALL_SELF,

    PERMISSIONS.USER_READ_SELF,
    PERMISSIONS.USER_UPDATE_SELF,
    PERMISSIONS.USER_DELETE_SELF,

    PERMISSIONS.FILE_CREATE_SELF,
    PERMISSIONS.FILE_READ_SELF,
    PERMISSIONS.FILE_UPDATE_SELF,
    PERMISSIONS.FILE_DELETE_SELF,
    PERMISSIONS.FILE_SHARE_SELF,

    PERMISSIONS.FOLDER_CREATE_SELF,
    PERMISSIONS.FOLDER_READ_SELF,
    PERMISSIONS.FOLDER_UPDATE_SELF,
    PERMISSIONS.FOLDER_DELETE_SELF,
  ],

  manager: [
    PERMISSIONS.AUTH_LOGOUT_SELF,
    PERMISSIONS.AUTH_LOGOUT_ALL_SELF,

    PERMISSIONS.USER_READ_SELF,
    PERMISSIONS.USER_UPDATE_SELF,
    PERMISSIONS.USER_DELETE_SELF,

    PERMISSIONS.FILE_CREATE_SELF,
    PERMISSIONS.FILE_READ_SELF,
    PERMISSIONS.FILE_UPDATE_SELF,
    PERMISSIONS.FILE_DELETE_SELF,
    PERMISSIONS.FILE_SHARE_SELF,

    PERMISSIONS.FOLDER_CREATE_SELF,
    PERMISSIONS.FOLDER_READ_SELF,
    PERMISSIONS.FOLDER_UPDATE_SELF,
    PERMISSIONS.FOLDER_DELETE_SELF,

    PERMISSIONS.USER_VIEW,
    PERMISSIONS.USER_ENABLE,
    PERMISSIONS.USER_DISABLE,
    PERMISSIONS.USER_CHANGE_ROLE,

    PERMISSIONS.FILE_VIEW_ANY,
  ],

  admin: Object.values(PERMISSIONS),
  owner: Object.values(PERMISSIONS),
};
